[package]
name = "happypto-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5.4", features = ["full"] }
tokio = { version = "1", features = ["full"] }
eyre = "0.6.12"
futures-util = "0.3.31"